// Amazon QuickSight calculated-field functions and the order of evaluation, taken from the AWS docs
// (functions-by-category, level-aware-calculations, order-of-evaluation-quicksight and each
// <name>-function.html page). Retrieved 2026-09-26. Pure data: no imports, no runtime dependencies.

export type FunctionKind = 'scalar' | 'aggregate' | 'table-calc' | 'lac-w';
export type CalcLevel = 'PRE_FILTER' | 'PRE_AGG' | 'POST_AGG_FILTER';

export interface QuickSightFunction {
  /** Exactly as written in an expression, e.g. 'sumOver', 'ifelse', 'distinct_count'. */
  name: string;
  /** The docs' category name. */
  category: string;
  /** scalar = row-level; aggregate; table-calc = window over the aggregated result; lac-w = window with a calc level. */
  kind: FunctionKind;
  /** As the docs show it (placeholder markup removed). */
  signature: string;
  summary: string;
  /** Aggregate that accepts a level-aware partition list `[ {dim}, ... ]` (LAC-A). */
  lacA?: boolean;
  /** Calculation levels it accepts, where documented. */
  calcLevels?: CalcLevel[];
  defaultCalcLevel?: CalcLevel;
  docUrl: string;
}

const DOCS = 'https://docs.aws.amazon.com/quicksight/latest/user/';
const doc = (name: string): string => `${DOCS}${name}-function.html`;

const ALL_LEVELS: CalcLevel[] = ['PRE_FILTER', 'PRE_AGG', 'POST_AGG_FILTER'];

export const ORDER_OF_EVALUATION_URL = `${DOCS}order-of-evaluation-quicksight.html`;
export const LEVEL_AWARE_CALCULATIONS_URL = `${DOCS}level-aware-calculations.html`;

export const QUICKSIGHT_FUNCTIONS: readonly QuickSightFunction[] = [
  // Aggregate
  {
    name: 'avg',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'avg(decimal, [group-by level])',
    summary: 'Average of a measure, grouped by the visual dimensions or a LAC-A level.',
    lacA: true,
    docUrl: doc('avg'),
  },
  {
    name: 'avgIf',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'avgIf(dimension or measure, condition)',
    summary: 'Average of the rows that meet a condition.',
    docUrl: doc('avgIf'),
  },
  {
    name: 'count',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'count(dimension or measure, [group-by level])',
    summary: 'Number of values, grouped by the visual dimensions or a LAC-A level.',
    lacA: true,
    docUrl: doc('count'),
  },
  {
    name: 'countIf',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'countIf(dimension or measure, condition)',
    summary: 'Number of values in the rows that meet a condition.',
    docUrl: doc('countIf'),
  },
  {
    name: 'distinct_count',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'distinct_count(dimension or measure, [group-by level])',
    summary: 'Number of distinct values, grouped by the visual dimensions or a LAC-A level.',
    lacA: true,
    docUrl: doc('distinct_count'),
  },
  {
    name: 'distinct_countIf',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'distinct_countIf(dimension or measure, condition)',
    summary: 'Number of distinct values in the rows that meet a condition.',
    docUrl: doc('distinct_countIf'),
  },
  {
    name: 'max',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'max(measure, [group-by level])',
    summary: 'Largest value of a measure, grouped by the visual dimensions or a LAC-A level.',
    lacA: true,
    docUrl: doc('max'),
  },
  {
    name: 'maxIf',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'maxIf(measure, condition)',
    summary: 'Largest value in the rows that meet a condition.',
    docUrl: doc('maxIf'),
  },
  {
    name: 'median',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'median(measure, [group-by level])',
    summary: 'Median of a measure, grouped by the visual dimensions or a LAC-A level.',
    lacA: true,
    docUrl: doc('median'),
  },
  {
    name: 'medianIf',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'medianIf(measure, condition)',
    summary: 'Median of the rows that meet a condition.',
    docUrl: doc('medianIf'),
  },
  {
    name: 'min',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'min(measure, [group-by level])',
    summary: 'Smallest value of a measure, grouped by the visual dimensions or a LAC-A level.',
    lacA: true,
    docUrl: doc('min'),
  },
  {
    name: 'minIf',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'minIf(measure, condition)',
    summary: 'Smallest value in the rows that meet a condition.',
    docUrl: doc('minIf'),
  },
  {
    name: 'percentile',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'percentile(expression, percentile, [group-by level])',
    summary: 'Alias of percentileDisc: the nth percentile using actual values of the measure.',
    lacA: true,
    docUrl: doc('percentile'),
  },
  {
    name: 'percentileCont',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'percentileCont(expression, percentile, [group-by level])',
    summary: 'The nth percentile interpolated over a continuous distribution of the measure.',
    lacA: true,
    docUrl: doc('percentileCont'),
  },
  {
    name: 'percentileDisc',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'percentileDisc(expression, percentile, [group-by level])',
    summary: 'The nth percentile picked from the actual values of the measure.',
    lacA: true,
    docUrl: doc('percentileDisc'),
  },
  {
    name: 'periodToDateAvg',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'periodToDateAvg(measure, dateTime, period, endDate (optional))',
    summary: 'Average of a measure from the start of a period (e.g. quarter) up to a date.',
    docUrl: doc('periodToDateAvg'),
  },
  {
    name: 'periodToDateCount',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'periodToDateCount(measure, dateTime, period, endDate (optional))',
    summary: 'Count of values, duplicates included, from the start of a period up to a date.',
    docUrl: doc('periodToDateCount'),
  },
  {
    name: 'periodToDateMax',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'periodToDateMax(measure, dateTime, period, endDate (optional))',
    summary: 'Largest value of a measure from the start of a period up to a date.',
    docUrl: doc('periodToDateMax'),
  },
  {
    name: 'periodToDateMedian',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'periodToDateMedian(measure, dateTime, period, endDate (optional))',
    summary: 'Median of a measure from the start of a period up to a date.',
    docUrl: doc('periodToDateMedian'),
  },
  {
    name: 'periodToDateMin',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'periodToDateMin(measure, dateTime, period, endDate (optional))',
    summary: 'Smallest value of a measure or date from the start of a period up to a date.',
    docUrl: doc('periodToDateMin'),
  },
  {
    name: 'periodToDatePercentile',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'periodToDatePercentile(measure, percentile, dateTime, period, endDate (optional))',
    summary: 'Percentile of actual values from the start of a period up to a date.',
    docUrl: doc('periodToDatePercentile'),
  },
  {
    name: 'periodToDatePercentileCont',
    category: 'Aggregate',
    kind: 'aggregate',
    signature:
      'periodToDatePercentileCont(measure, percentile, dateTime, period, endDate (optional))',
    summary: 'Continuous-distribution percentile from the start of a period up to a date.',
    docUrl: doc('periodToDatePercentileCont'),
  },
  {
    name: 'periodToDateStDev',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'periodToDateStDev(measure, dateTime, period, endDate (optional))',
    summary: 'Sample standard deviation from the start of a period up to a date.',
    docUrl: doc('periodToDateStDev'),
  },
  {
    name: 'periodToDateStDevP',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'periodToDateStDevP(measure, dateTime, period, endDate (optional))',
    summary: 'Population standard deviation from the start of a period up to a date.',
    docUrl: doc('periodToDateStDevP'),
  },
  {
    name: 'periodToDateSum',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'periodToDateSum(measure, dateTime, period, endDate)',
    summary: 'Sum of a measure from the start of a period up to a date.',
    docUrl: doc('periodToDateSum'),
  },
  {
    name: 'periodToDateVar',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'periodToDateVar(measure, dateTime, period, endDate (optional))',
    summary: 'Sample variance from the start of a period up to a date.',
    docUrl: doc('periodToDateVar'),
  },
  {
    name: 'periodToDateVarP',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'periodToDateVarP(measure, dateTime, period, endDate (optional))',
    summary: 'Population variance from the start of a period up to a date.',
    docUrl: doc('periodToDateVarP'),
  },
  {
    name: 'stdev',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'stdev(measure, [group-by level])',
    summary: 'Sample standard deviation, grouped by the visual dimensions or a LAC-A level.',
    lacA: true,
    docUrl: doc('stdev'),
  },
  {
    name: 'stdevIf',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'stdevIf(measure, conditions)',
    summary: 'Sample standard deviation of the rows that meet a condition.',
    docUrl: doc('stdevIf'),
  },
  {
    name: 'stdevp',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'stdevp(measure, [group-by level])',
    summary: 'Population standard deviation, grouped by the visual dimensions or a LAC-A level.',
    lacA: true,
    docUrl: doc('stdevp'),
  },
  {
    name: 'stdevpIf',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'stdevpIf(measure, conditions)',
    summary: 'Population standard deviation of the rows that meet a condition.',
    docUrl: doc('stdevpIf'),
  },
  {
    name: 'sum',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'sum(measure, [group-by level])',
    summary: 'Sum of a measure, grouped by the visual dimensions or a LAC-A level.',
    lacA: true,
    docUrl: doc('sum'),
  },
  {
    name: 'sumIf',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'sumIf(measure, conditions)',
    summary: 'Sum of the rows that meet a condition.',
    docUrl: doc('sumIf'),
  },
  {
    name: 'var',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'var(measure, [group-by level])',
    summary: 'Sample variance, grouped by the visual dimensions or a LAC-A level.',
    lacA: true,
    docUrl: doc('var'),
  },
  {
    name: 'varIf',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'varIf(measure, conditions)',
    summary: 'Sample variance of the rows that meet a condition.',
    docUrl: doc('varIf'),
  },
  {
    name: 'varp',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'varp(measure, [group-by level])',
    summary: 'Population variance, grouped by the visual dimensions or a LAC-A level.',
    lacA: true,
    docUrl: doc('varp'),
  },
  {
    name: 'varpIf',
    category: 'Aggregate',
    kind: 'aggregate',
    signature: 'varpIf(measure, conditions)',
    summary: 'Population variance of the rows that meet a condition.',
    docUrl: doc('varpIf'),
  },

  // Conditional
  {
    name: 'coalesce',
    category: 'Conditional',
    kind: 'scalar',
    signature: 'coalesce(expression1, expression2 [, expression3, ...])',
    summary: 'The first argument that is not null.',
    docUrl: doc('coalesce'),
  },
  {
    name: 'ifelse',
    category: 'Conditional',
    kind: 'scalar',
    signature:
      'ifelse(if-expression-1, then-expression-1 [, if-expression-n, then-expression-n ...], else-expression)',
    summary: 'The value paired with the first condition that is true, else the default.',
    docUrl: doc('ifelse'),
  },
  {
    name: 'in',
    category: 'Conditional',
    kind: 'scalar',
    signature: 'in(expression, [literal-1, ...])',
    summary: 'True when the value is in a list of literals or a multivalue parameter.',
    docUrl: doc('in'),
  },
  {
    name: 'isNotNull',
    category: 'Conditional',
    kind: 'scalar',
    signature: 'isNotNull(expression)',
    summary: 'True when the value is not null.',
    docUrl: doc('isNotNull'),
  },
  {
    name: 'isNull',
    category: 'Conditional',
    kind: 'scalar',
    signature: 'isNull(expression)',
    summary: 'True when the value is null.',
    docUrl: doc('isNull'),
  },
  {
    name: 'notIn',
    category: 'Conditional',
    kind: 'scalar',
    signature: 'notIn(expression, [literal-1, ...])',
    summary: 'True when the value is not in a list of literals or a multivalue parameter.',
    docUrl: doc('notIn'),
  },
  {
    name: 'nullIf',
    category: 'Conditional',
    kind: 'scalar',
    signature: 'nullIf(expression1, expression2)',
    summary: 'Null when the two expressions are equal, otherwise the first.',
    docUrl: doc('nullIf'),
  },
  {
    name: 'switch',
    category: 'Conditional',
    kind: 'scalar',
    signature:
      'switch(condition-expression, label-1, return-expression-1 [, label-n, return-expression-n ...], default-expression)',
    summary: 'The result paired with the first label equal to the condition, else the default.',
    docUrl: doc('switch'),
  },

  // Date
  {
    name: 'addDateTime',
    category: 'Date',
    kind: 'scalar',
    signature: 'addDateTime(amount, period, datetime)',
    summary: 'Adds (or subtracts) an amount of a time unit to a date.',
    docUrl: doc('addDateTime'),
  },
  {
    name: 'addWorkDays',
    category: 'Date',
    kind: 'scalar',
    signature: 'addWorkDays(initDate, numWorkDays)',
    summary: 'Adds (or subtracts) a number of work days to a date.',
    docUrl: doc('addWorkDays'),
  },
  {
    name: 'dateDiff',
    category: 'Date',
    kind: 'scalar',
    signature: 'dateDiff(date1, date2, [period])',
    summary: 'Difference between two dates, in days unless a period is given.',
    docUrl: doc('dateDiff'),
  },
  {
    name: 'epochDate',
    category: 'Date',
    kind: 'scalar',
    signature: 'epochDate(epochdate)',
    summary: 'Converts epoch seconds to a date (SPICE datasets only).',
    docUrl: doc('epochDate'),
  },
  {
    name: 'extract',
    category: 'Date',
    kind: 'scalar',
    signature: 'extract(period, date)',
    summary: 'One part of a date, such as the year or the hour.',
    docUrl: doc('extract'),
  },
  {
    name: 'formatDate',
    category: 'Date',
    kind: 'scalar',
    signature: "formatDate(date, ['format'])",
    summary: 'Formats a date as a string using a pattern.',
    docUrl: doc('formatDate'),
  },
  {
    name: 'isWorkDay',
    category: 'Date',
    kind: 'scalar',
    signature: 'isWorkDay(inputDate)',
    summary: 'Whether a date is a work day (returns 1 or 0).',
    docUrl: doc('isWorkDay'),
  },
  {
    name: 'netWorkDays',
    category: 'Date',
    kind: 'scalar',
    signature: 'netWorkDays(startDate, endDate)',
    summary: 'Number of work days between two dates.',
    docUrl: doc('netWorkDays'),
  },
  {
    name: 'now',
    category: 'Date',
    kind: 'scalar',
    signature: 'now()',
    summary: 'The current date and time.',
    docUrl: doc('now'),
  },
  {
    name: 'truncDate',
    category: 'Date',
    kind: 'scalar',
    signature: "truncDate('period', date)",
    summary: 'A date truncated to the start of a period, such as the month.',
    docUrl: doc('truncDate'),
  },

  // Numeric
  {
    name: 'ceil',
    category: 'Numeric',
    kind: 'scalar',
    signature: 'ceil(decimal)',
    summary: 'Rounds a decimal up to the next integer.',
    docUrl: doc('ceil'),
  },
  {
    name: 'decimalToInt',
    category: 'Numeric',
    kind: 'scalar',
    signature: 'decimalToInt(decimal)',
    summary: 'Converts a decimal to an integer by dropping the fraction.',
    docUrl: doc('decimalToInt'),
  },
  {
    name: 'floor',
    category: 'Numeric',
    kind: 'scalar',
    signature: 'floor(decimal)',
    summary: 'Rounds a decimal down to the next integer.',
    docUrl: doc('floor'),
  },
  {
    name: 'intToDecimal',
    category: 'Numeric',
    kind: 'scalar',
    signature: 'intToDecimal(integer)',
    summary: 'Converts an integer to a decimal.',
    docUrl: doc('intToDecimal'),
  },
  {
    name: 'round',
    category: 'Numeric',
    kind: 'scalar',
    signature: 'round(decimal, scale)',
    summary: 'Rounds to the nearest integer, or to a number of decimal places.',
    docUrl: doc('round'),
  },

  // Mathematical
  {
    name: 'abs',
    category: 'Mathematical',
    kind: 'scalar',
    signature: 'abs(expression)',
    summary: 'Absolute value.',
    docUrl: doc('abs'),
  },
  {
    name: 'exp',
    category: 'Mathematical',
    kind: 'scalar',
    signature: 'exp(expression)',
    summary: 'e raised to the power of the expression.',
    docUrl: doc('exp'),
  },
  {
    name: 'ln',
    category: 'Mathematical',
    kind: 'scalar',
    signature: 'ln(expression)',
    summary: 'Natural logarithm.',
    docUrl: doc('ln'),
  },
  {
    name: 'log',
    category: 'Mathematical',
    kind: 'scalar',
    signature: 'log(expression)',
    summary: 'Base-10 logarithm.',
    docUrl: doc('log'),
  },
  {
    name: 'mod',
    category: 'Mathematical',
    kind: 'scalar',
    signature: 'mod(number, divisor)',
    summary: 'Remainder after division; the % operator does the same.',
    docUrl: doc('mod'),
  },
  {
    name: 'sqrt',
    category: 'Mathematical',
    kind: 'scalar',
    signature: 'sqrt(expression)',
    summary: 'Square root.',
    docUrl: doc('sqrt'),
  },

  // String
  {
    name: 'concat',
    category: 'String',
    kind: 'scalar',
    signature: 'concat(expression1, expression2 [, expression3 ...])',
    summary: 'Joins two or more strings.',
    docUrl: doc('concat'),
  },
  {
    name: 'contains',
    category: 'String',
    kind: 'scalar',
    signature: 'contains(expression, substring, string-comparison-mode)',
    summary: 'Whether a string contains a substring, case-sensitive unless told otherwise.',
    docUrl: doc('contains'),
  },
  {
    name: 'endsWith',
    category: 'String',
    kind: 'scalar',
    signature: 'endsWith(expression, substring, string-comparison-mode)',
    summary: 'Whether a string ends with a substring.',
    docUrl: doc('endsWith'),
  },
  {
    name: 'left',
    category: 'String',
    kind: 'scalar',
    signature: 'left(expression, limit)',
    summary: 'The leftmost characters of a string.',
    docUrl: doc('left'),
  },
  {
    name: 'locate',
    category: 'String',
    kind: 'scalar',
    signature: 'locate(expression, substring, start)',
    summary: '1-based position of a substring, or 0 when it is absent.',
    docUrl: doc('locate'),
  },
  {
    name: 'ltrim',
    category: 'String',
    kind: 'scalar',
    signature: 'ltrim(expression)',
    summary: 'Removes leading blanks.',
    docUrl: doc('ltrim'),
  },
  {
    name: 'parseDate',
    category: 'String',
    kind: 'scalar',
    signature: "parseDate(expression, ['format'])",
    summary: 'Parses a string into a date, skipping rows that do not match the format.',
    docUrl: doc('parseDate'),
  },
  {
    name: 'parseDecimal',
    category: 'String',
    kind: 'scalar',
    signature: 'parseDecimal(expression)',
    summary: 'Parses a string into a decimal, skipping rows that are not numeric.',
    docUrl: doc('parseDecimal'),
  },
  {
    name: 'parseInt',
    category: 'String',
    kind: 'scalar',
    signature: 'parseInt(expression)',
    summary: 'Parses a string into an integer, rounding decimals down.',
    docUrl: doc('parseInt'),
  },
  {
    name: 'parseJson',
    category: 'String',
    kind: 'scalar',
    signature: 'parseJson(fieldName, path)',
    summary: 'Extracts a value from JSON by path; on SPICE only in data preparation.',
    docUrl: doc('parseJson'),
  },
  {
    name: 'replace',
    category: 'String',
    kind: 'scalar',
    signature: 'replace(expression, substring, replacement)',
    summary: 'Replaces every occurrence of a substring.',
    docUrl: doc('replace'),
  },
  {
    name: 'right',
    category: 'String',
    kind: 'scalar',
    signature: 'right(expression, limit)',
    summary: 'The rightmost characters of a string.',
    docUrl: doc('right'),
  },
  {
    name: 'rtrim',
    category: 'String',
    kind: 'scalar',
    signature: 'rtrim(expression)',
    summary: 'Removes trailing blanks.',
    docUrl: doc('rtrim'),
  },
  {
    name: 'split',
    category: 'String',
    kind: 'scalar',
    signature: 'split(expression, delimiter, position)',
    summary: 'The nth piece of a delimited string; data preparation only, not in analyses.',
    docUrl: doc('split'),
  },
  {
    name: 'startsWith',
    category: 'String',
    kind: 'scalar',
    signature: 'startsWith(expression, substring, string-comparison-mode)',
    summary: 'Whether a string starts with a substring.',
    docUrl: doc('startsWith'),
  },
  {
    name: 'strlen',
    category: 'String',
    kind: 'scalar',
    signature: 'strlen(expression)',
    summary: 'Number of characters, spaces included.',
    docUrl: doc('strlen'),
  },
  {
    name: 'substring',
    category: 'String',
    kind: 'scalar',
    signature: 'substring(expression, start, length)',
    summary: 'Characters from a 1-based start position for a given length.',
    docUrl: doc('substring'),
  },
  {
    name: 'toLower',
    category: 'String',
    kind: 'scalar',
    signature: 'toLower(expression)',
    summary: 'Lower-cases a string.',
    docUrl: doc('toLower'),
  },
  {
    name: 'toString',
    category: 'String',
    kind: 'scalar',
    signature: 'toString(expression)',
    summary: 'Formats any value as a string.',
    docUrl: doc('toString'),
  },
  {
    name: 'toUpper',
    category: 'String',
    kind: 'scalar',
    signature: 'toUpper(expression)',
    summary: 'Upper-cases a string.',
    docUrl: doc('toUpper'),
  },
  {
    name: 'trim',
    category: 'String',
    kind: 'scalar',
    signature: 'trim(expression)',
    summary: 'Removes leading and trailing blanks.',
    docUrl: doc('trim'),
  },

  // Table calculation: lookup
  {
    name: 'difference',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'difference(measure, [ sortorder_field ASC_or_DESC, ... ], lookup_index, [ partition field, ... ])',
    summary: 'Difference between the current value and one a number of rows away.',
    docUrl: doc('difference'),
  },
  {
    name: 'lag',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'lag(measure, [ sortorder_field ASC_or_DESC, ... ], lookup_index, [ partition_field, ... ])',
    summary: 'The value a number of rows before the current one.',
    docUrl: doc('lag'),
  },
  {
    name: 'lead',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'lead(measure, [ sortorder_field ASC_or_DESC, ... ], lookup_index, [ partition_field, ... ])',
    summary: 'The value a number of rows after the current one.',
    docUrl: doc('lead'),
  },
  {
    name: 'percentDifference',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'percentDifference(measure, [ sortorder_field ASC_or_DESC, ... ], lookup index, [ partition_field, ... ])',
    summary: 'Percentage difference between the current value and one a number of rows away.',
    docUrl: doc('percentDifference'),
  },

  // Table calculation: over (the LAC-W ones take a calculation level)
  {
    name: 'avgOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'avgOver(measure, [ partition_field, ... ], calculation level)',
    summary: 'Average of a measure over a partition.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('avgOver'),
  },
  {
    name: 'countOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'countOver(measure or dimension field, [ partition_field, ... ], calculation level)',
    summary: 'Count of a field over a partition.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('countOver'),
  },
  {
    name: 'distinctCountOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature:
      'distinctCountOver(measure or dimension field, [ partition_field, ... ], calculation level)',
    summary: 'Distinct count of an unaggregated field over a partition.',
    calcLevels: ['PRE_FILTER', 'PRE_AGG'],
    docUrl: doc('distinctCountOver'),
  },
  {
    name: 'maxOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'maxOver(measure, [ partition_field, ... ], calculation level)',
    summary: 'Largest value of a measure over a partition.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('maxOver'),
  },
  {
    name: 'minOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'minOver(measure, [ partition_field, ... ], calculation level)',
    summary: 'Smallest value of a measure over a partition.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('minOver'),
  },
  {
    name: 'percentileOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'percentileOver(measure, percentile-n, [partition-by, …], calculation-level)',
    summary: 'Alias of percentileDiscOver.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('percentileOver'),
  },
  {
    name: 'percentileContOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'percentileContOver(measure, percentile-n, [partition-by, …], calculation-level)',
    summary: 'Continuous-distribution percentile of a measure over a partition.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('percentileContOver'),
  },
  {
    name: 'percentileDiscOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'percentileDiscOver(measure, percentile-n, [partition-by, …], calculation-level)',
    summary: 'Percentile of the actual values of a measure over a partition.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('percentileDiscOver'),
  },
  {
    name: 'percentOfTotal',
    category: 'Table calculation',
    kind: 'table-calc',
    signature: 'percentOfTotal(measure, [ partition_field, ... ])',
    summary: 'Share of the partition total that each value contributes.',
    docUrl: doc('percentOfTotal'),
  },
  {
    name: 'periodOverPeriodDifference',
    category: 'Table calculation',
    kind: 'table-calc',
    signature: 'periodOverPeriodDifference(measure, date, period, offset)',
    summary: 'Difference between a measure now and in an earlier period.',
    docUrl: doc('periodOverPeriodDifference'),
  },
  {
    name: 'periodOverPeriodLastValue',
    category: 'Table calculation',
    kind: 'table-calc',
    signature: 'periodOverPeriodLastValue(measure, date, period, offset)',
    summary: 'The value of a measure in an earlier period.',
    docUrl: doc('periodOverPeriodLastValue'),
  },
  {
    name: 'periodOverPeriodPercentDifference',
    category: 'Table calculation',
    kind: 'table-calc',
    signature: 'periodOverPeriodPercentDifference(measure, date, period, offset)',
    summary: 'Percentage difference between a measure now and in an earlier period.',
    docUrl: doc('periodOverPeriodPercentDifference'),
  },
  {
    name: 'periodToDateAvgOverTime',
    category: 'Table calculation',
    kind: 'table-calc',
    signature: 'periodToDateAvgOverTime(measure, dateTime, period)',
    summary: 'Period-to-date average at each point of the visual timeline.',
    docUrl: doc('periodToDateAvgOverTime'),
  },
  {
    name: 'periodToDateCountOverTime',
    category: 'Table calculation',
    kind: 'table-calc',
    signature: 'periodToDateCountOverTime(measure, dateTime, period)',
    summary: 'Period-to-date count at each point of the visual timeline.',
    docUrl: doc('periodToDateCountOverTime'),
  },
  {
    name: 'periodToDateMaxOverTime',
    category: 'Table calculation',
    kind: 'table-calc',
    signature: 'periodToDateMaxOverTime(measure, dateTime, period)',
    summary: 'Period-to-date maximum at each point of the visual timeline.',
    docUrl: doc('periodToDateMaxOverTime'),
  },
  {
    name: 'periodToDateMinOverTime',
    category: 'Table calculation',
    kind: 'table-calc',
    signature: 'periodToDateMinOverTime(measure, dateTime, period)',
    summary: 'Period-to-date minimum at each point of the visual timeline.',
    docUrl: doc('periodToDateMinOverTime'),
  },
  {
    name: 'periodToDateSumOverTime',
    category: 'Table calculation',
    kind: 'table-calc',
    signature: 'periodToDateSumOverTime(measure, dateTime, period)',
    summary: 'Period-to-date sum at each point of the visual timeline.',
    docUrl: doc('periodToDateSumOverTime'),
  },
  {
    name: 'stdevOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'stdevOver(measure, [ partition_field, ... ], calculation level)',
    summary: 'Sample standard deviation of a measure over a partition.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('stdevOver'),
  },
  {
    name: 'stdevpOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'stdevpOver(measure, [ partition_field, ... ], calculation level)',
    summary: 'Population standard deviation of a measure over a partition.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('stdevpOver'),
  },
  {
    name: 'sumOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'sumOver(measure, [ partition_field, ... ], calculation level)',
    summary: 'Sum of a measure over a partition.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('sumOver'),
  },
  {
    name: 'varOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'varOver(measure, [ partition_field, ... ], calculation level)',
    summary: 'Sample variance of a measure over a partition.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('varOver'),
  },
  {
    name: 'varpOver',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'varpOver(measure, [ partition_field, ... ], calculation level)',
    summary: 'Population variance of a measure over a partition.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('varpOver'),
  },

  // Table calculation: ranking (LAC-W; the level is an argument after the partition list)
  {
    name: 'rank',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'rank([ sort_order_field ASC_or_DESC, ... ], [ partition_field, ... ])',
    summary: 'Rank within a partition, leaving gaps after ties.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('rank'),
  },
  {
    name: 'denseRank',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'denseRank([ sort_order_field ASC_or_DESC, ... ], [ partition_field, ... ])',
    summary: 'Rank within a partition without gaps after ties.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('denseRank'),
  },
  {
    name: 'percentileRank',
    category: 'Table calculation',
    kind: 'lac-w',
    signature: 'percentileRank([ sort_order_field ASC_or_DESC, ... ], [ partition_field, ... ])',
    summary: 'Percentile rank within a partition, from 0 up to but excluding 100.',
    calcLevels: ALL_LEVELS,
    defaultCalcLevel: 'POST_AGG_FILTER',
    docUrl: doc('percentileRank'),
  },

  // Table calculation: running
  {
    name: 'runningAvg',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'runningAvg(measure, [ sortorder_field ASC_or_DESC, ... ], [ partition_field, ... ])',
    summary: 'Running average in sort order.',
    docUrl: doc('runningAvg'),
  },
  {
    name: 'runningCount',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'runningCount(measure_or_dimension, [ sortorder_field ASC_or_DESC, ... ], [ partition_field, ... ])',
    summary: 'Running count in sort order.',
    docUrl: doc('runningCount'),
  },
  {
    name: 'runningMax',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'runningMax(measure, [ sortorder_field ASC_or_DESC, ... ], [ partition_field, ... ])',
    summary: 'Running maximum in sort order.',
    docUrl: doc('runningMax'),
  },
  {
    name: 'runningMin',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'runningMin(measure, [ sortorder_field ASC_or_DESC, ... ], [ partition_field, ... ])',
    summary: 'Running minimum in sort order.',
    docUrl: doc('runningMin'),
  },
  {
    name: 'runningSum',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'runningSum(measure, [ sortorder_field ASC_or_DESC, ... ], [ partition_field, ... ])',
    summary: 'Running total in sort order.',
    docUrl: doc('runningSum'),
  },

  // Table calculation: window
  {
    name: 'firstValue',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'firstValue(aggregated measure or dimension, [ sort_attribute ASC_or_DESC, ... ], [ partition_by_attribute, ... ])',
    summary: 'The first value in each sorted partition.',
    docUrl: doc('firstValue'),
  },
  {
    name: 'lastValue',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'lastValue(aggregated measure or dimension, [ sort_attribute ASC_or_DESC, ... ], [ partition_by_attribute, ... ])',
    summary: 'The last value in each sorted partition.',
    docUrl: doc('lastValue'),
  },
  {
    name: 'windowAvg',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'windowAvg(measure, [sort_order_field ASC/DESC, ...], start_index, end_index, [ partition_field, ... ])',
    summary: 'Average over a window of rows around the current one.',
    docUrl: doc('windowAvg'),
  },
  {
    name: 'windowCount',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'windowCount(measure_or_dimension, [sort_order_field ASC/DESC, ...], start_index, end_index, [ partition_field, ... ])',
    summary: 'Count over a window of rows around the current one.',
    docUrl: doc('windowCount'),
  },
  {
    name: 'windowMax',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'windowMax(measure, [sort_order_field ASC/DESC, ...], start_index, end_index, [ partition_field, ... ])',
    summary: 'Maximum over a window of rows around the current one.',
    docUrl: doc('windowMax'),
  },
  {
    name: 'windowMin',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'windowMin(measure, [sort_order_field ASC/DESC, ...], start_index, end_index, [ partition_field, ... ])',
    summary: 'Minimum over a window of rows around the current one.',
    docUrl: doc('windowMin'),
  },
  {
    name: 'windowSum',
    category: 'Table calculation',
    kind: 'table-calc',
    signature:
      'windowSum(measure, [sort_order_field ASC/DESC, ...], start_index, end_index, [ partition_field, ... ])',
    summary: 'Sum over a window of rows around the current one.',
    docUrl: doc('windowSum'),
  },
];

export interface EvaluationStage {
  id: string;
  label: string;
  summary: string;
}

/**
 * The docs' order of evaluation inside an analysis, first to last. Everything set up on the
 * dataset (dataset calculated fields, dataset filters, row-level security) happens before this,
 * on the underlying data. The docs group the steps into four levels: LAC-W prefilter
 * (simple calculations, PRE_FILTER), LAC-W PRE_AGG (analysis filters, PRE_AGG, top/bottom N),
 * LAC-A (custom-level aggregations) and visual (the rest).
 */
export const EVALUATION_ORDER: readonly EvaluationStage[] = [
  {
    id: 'dataset',
    label: 'Data set',
    summary: 'Dataset calculations, filters and security settings, applied to the underlying data.',
  },
  {
    id: 'simple-calculations',
    label: 'Simple calculations',
    summary: 'Row-level (scalar) calculations with no aggregation or window, at table cardinality.',
  },
  {
    id: 'lac-w-pre-filter',
    label: 'LAC-W function PRE_FILTER',
    summary: 'Window functions at PRE_FILTER run on the whole table, and filters on them apply.',
  },
  {
    id: 'analysis-filters',
    label: 'Filters added during analysis',
    summary: 'Filters on unaggregated fields, like a WHERE clause.',
  },
  {
    id: 'lac-w-pre-agg',
    label: 'LAC-W function PRE_AGG',
    summary: 'Window functions at PRE_AGG run on the filtered rows, and filters on them apply.',
  },
  {
    id: 'top-bottom-n',
    label: 'Top/bottom N filters',
    summary: 'Filters on dimensions that keep the top or bottom N items.',
  },
  {
    id: 'lac-a',
    label: 'Custom-level aggregations',
    summary: 'LAC-A aggregations, grouped by the dimensions named in the calculation.',
  },
  {
    id: 'visual-aggregations',
    label: 'Visual-level aggregations',
    summary: 'Aggregations grouped by the visual dimensions; filters on them apply, like HAVING.',
  },
  {
    id: 'table-calculations',
    label: 'Table calculations',
    summary: 'Post-aggregation window calculations (POST_AGG_FILTER), and filters on them.',
  },
  {
    id: 'other-category',
    label: 'Other category calculations',
    summary: 'The "Other" bucket in line, bar, pie and donut charts.',
  },
  {
    id: 'totals',
    label: 'Totals and subtotals',
    summary: 'Totals and subtotals in tables, pivot tables and donut charts, when requested.',
  },
];
